packages:
  - apps/*
  - '!apps/dreamchasers'
  - '!apps/dreamchasers-db22c983'
  - packages/*

hoist: false

minimumReleaseAge: 1400

minimumReleaseAgeExclude:
  - next
  - '@next/third-parties'
  - '@next/env'
  - '@next/swc-darwin-arm64'
  - '@next/swc-darwin-x64'
  - '@next/swc-linux-arm64-gnu'
  - '@next/swc-linux-arm64-musl'
  - '@next/swc-linux-x64-gnu'
  - '@next/swc-linux-x64-musl'
  - '@next/swc-win32-x64-msvc'
  - '@next/swc-win32-arm64-msvc'

# https://github.com/prisma/prisma/issues/29123
overrides:
  '@hono/node-server@<1.19.10': '>=1.19.10'
  hono@<4.11.10: '>=4.11.10'
  hono@<4.11.7: '>=4.11.7'
  hono@<4.12.4: '>=4.12.4'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
