packages:
  - apps/*
  - packages/*

minimumReleaseAge: 1400

minimumReleaseAgeExclude:
  - next
  - "@next/env"
  - "@next/swc-darwin-arm64"
  - "@next/swc-darwin-x64"
  - "@next/swc-linux-arm64-gnu"
  - "@next/swc-linux-arm64-musl"
  - "@next/swc-linux-x64-gnu"
  - "@next/swc-linux-x64-musl"
  - "@next/swc-win32-x64-msvc"
  - "@next/swc-win32-arm64-msvc"

hoist: false
