packages:
  - apps/*
  - "!apps/dreamchasers"
  - "!apps/dreamchasers-db22c983"
  - packages/*

hoist: false

# https://github.com/prisma/prisma/issues/29123
overrides:
  "@hono/node-server@<1.19.10": ">=1.19.10"
  hono@<4.11.10: ">=4.11.10"
  hono@<4.11.7: ">=4.11.7"
  hono@<4.12.4: ">=4.12.4"
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"

catalog:
  tailwindcss: ^4
  "@tailwindcss/postcss": ^4
  typescript: ^5

catalogs:
  react:
    react: ^19
    react-dom: ^19
    "@types/react": ^19
    "@types/react-dom": ^19
    babel-plugin-react-compiler: ^1.0.0
  node22:
    "@types/node": ^22
  nextjs-canary:
    next: canary
    "@next/third-parties": canary
  prisma:
    prisma: 7.4.2
    "@prisma/client": 7.4.2
    "@prisma/adapter-pg": 7.4.2
