name: Bug Report
description: Report broken part of a website.
labels: bug
body:
  - type: markdown
    attributes:
      value: >
        Thanks for spotting a bug on your website, very appreciated!

        And sincere apologize to you for ruining your experience.

  - type: input
    attributes:
      label: Summary
      description: What is the bug?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: All the steps to trigger the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Results
      description: Desired results.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Results
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
