name: Feature Request
description: Suggest an idea for this website.
labels: feature-request
body:
  - type: input
    attributes:
      label: Summary
      description: Describe your feature.
    validations:
      required: true

  - type: textarea
    attributes:
      label: The Problem
      description: Why do you want us to add this feature?
    validations:
      required: true

  - type: textarea
    attributes:
      label: The Proposed Solution
      description: What do you have in mind to do this feature?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
