services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION: ${MINIO_REGION}
    command: server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 2s
      timeout: 10s
      retries: 5
    volumes:
      - ./storage:/data:z

  minio-createbucket:
      image: minio/mc:RELEASE.2025-08-13T08-35-41Z
      depends_on:
        minio:
          condition: service_healthy
      environment:
        MINIO_ROOT_USER: ${MINIO_ROOT_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        DEFAULT_BUCKET: ${DEFAULT_BUCKET}
      entrypoint: >
        /bin/sh -c "
        /usr/bin/mc alias set akvns http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD &&
        /usr/bin/mc mb akvns/$$DEFAULT_BUCKET &&
        exit 0
        "
