/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SitemapDotxmlRouteImport } from './app/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './app/robots[.]txt'
import { Route as vnsRouteRouteImport } from './app/(vns)/route'
import { Route as vnsIndexRouteImport } from './app/(vns)/index'
import { Route as vnsStationComm1RouteImport } from './app/(vns)/station-comm-1'
import { Route as vnsStaffRouteImport } from './app/(vns)/staff'
import { Route as vnsProjectsRouteImport } from './app/(vns)/projects'
import { Route as vnsComicIndexRouteImport } from './app/(vns)/comic/index'
import { Route as vnsComicSeriesRouteImport } from './app/(vns)/comic/$series'
import { Route as vnsApiSplatRouteImport } from './app/(vns)/api/$'
import { Route as vnsComicSeriesChapterRouteImport } from './app/(vns)/comic_/$series/$chapter'
import { Route as vnsApiAuthSplatRouteImport } from './app/(vns)/api/auth/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const vnsRouteRoute = vnsRouteRouteImport.update({
  id: '/(vns)',
  getParentRoute: () => rootRouteImport,
} as any)
const vnsIndexRoute = vnsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => vnsRouteRoute,
} as any)
const vnsStationComm1Route = vnsStationComm1RouteImport.update({
  id: '/station-comm-1',
  path: '/station-comm-1',
  getParentRoute: () => vnsRouteRoute,
} as any)
const vnsStaffRoute = vnsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => vnsRouteRoute,
} as any)
const vnsProjectsRoute = vnsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => vnsRouteRoute,
} as any)
const vnsComicIndexRoute = vnsComicIndexRouteImport.update({
  id: '/comic/',
  path: '/comic/',
  getParentRoute: () => vnsRouteRoute,
} as any)
const vnsComicSeriesRoute = vnsComicSeriesRouteImport.update({
  id: '/comic/$series',
  path: '/comic/$series',
  getParentRoute: () => vnsRouteRoute,
} as any)
const vnsApiSplatRoute = vnsApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => vnsRouteRoute,
} as any)
const vnsComicSeriesChapterRoute = vnsComicSeriesChapterRouteImport.update({
  id: '/comic_/$series/$chapter',
  path: '/comic/$series/$chapter',
  getParentRoute: () => vnsRouteRoute,
} as any)
const vnsApiAuthSplatRoute = vnsApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => vnsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects': typeof vnsProjectsRoute
  '/staff': typeof vnsStaffRoute
  '/station-comm-1': typeof vnsStationComm1Route
  '/': typeof vnsIndexRoute
  '/api/$': typeof vnsApiSplatRoute
  '/comic/$series': typeof vnsComicSeriesRoute
  '/comic': typeof vnsComicIndexRoute
  '/api/auth/$': typeof vnsApiAuthSplatRoute
  '/comic/$series/$chapter': typeof vnsComicSeriesChapterRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects': typeof vnsProjectsRoute
  '/staff': typeof vnsStaffRoute
  '/station-comm-1': typeof vnsStationComm1Route
  '/': typeof vnsIndexRoute
  '/api/$': typeof vnsApiSplatRoute
  '/comic/$series': typeof vnsComicSeriesRoute
  '/comic': typeof vnsComicIndexRoute
  '/api/auth/$': typeof vnsApiAuthSplatRoute
  '/comic/$series/$chapter': typeof vnsComicSeriesChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(vns)': typeof vnsRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(vns)/projects': typeof vnsProjectsRoute
  '/(vns)/staff': typeof vnsStaffRoute
  '/(vns)/station-comm-1': typeof vnsStationComm1Route
  '/(vns)/': typeof vnsIndexRoute
  '/(vns)/api/$': typeof vnsApiSplatRoute
  '/(vns)/comic/$series': typeof vnsComicSeriesRoute
  '/(vns)/comic/': typeof vnsComicIndexRoute
  '/(vns)/api/auth/$': typeof vnsApiAuthSplatRoute
  '/(vns)/comic_/$series/$chapter': typeof vnsComicSeriesChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/projects'
    | '/staff'
    | '/station-comm-1'
    | '/'
    | '/api/$'
    | '/comic/$series'
    | '/comic'
    | '/api/auth/$'
    | '/comic/$series/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/projects'
    | '/staff'
    | '/station-comm-1'
    | '/'
    | '/api/$'
    | '/comic/$series'
    | '/comic'
    | '/api/auth/$'
    | '/comic/$series/$chapter'
  id:
    | '__root__'
    | '/(vns)'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(vns)/projects'
    | '/(vns)/staff'
    | '/(vns)/station-comm-1'
    | '/(vns)/'
    | '/(vns)/api/$'
    | '/(vns)/comic/$series'
    | '/(vns)/comic/'
    | '/(vns)/api/auth/$'
    | '/(vns)/comic_/$series/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  vnsRouteRoute: typeof vnsRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(vns)': {
      id: '/(vns)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof vnsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(vns)/': {
      id: '/(vns)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof vnsIndexRouteImport
      parentRoute: typeof vnsRouteRoute
    }
    '/(vns)/station-comm-1': {
      id: '/(vns)/station-comm-1'
      path: '/station-comm-1'
      fullPath: '/station-comm-1'
      preLoaderRoute: typeof vnsStationComm1RouteImport
      parentRoute: typeof vnsRouteRoute
    }
    '/(vns)/staff': {
      id: '/(vns)/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof vnsStaffRouteImport
      parentRoute: typeof vnsRouteRoute
    }
    '/(vns)/projects': {
      id: '/(vns)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof vnsProjectsRouteImport
      parentRoute: typeof vnsRouteRoute
    }
    '/(vns)/comic/': {
      id: '/(vns)/comic/'
      path: '/comic'
      fullPath: '/comic'
      preLoaderRoute: typeof vnsComicIndexRouteImport
      parentRoute: typeof vnsRouteRoute
    }
    '/(vns)/comic/$series': {
      id: '/(vns)/comic/$series'
      path: '/comic/$series'
      fullPath: '/comic/$series'
      preLoaderRoute: typeof vnsComicSeriesRouteImport
      parentRoute: typeof vnsRouteRoute
    }
    '/(vns)/api/$': {
      id: '/(vns)/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof vnsApiSplatRouteImport
      parentRoute: typeof vnsRouteRoute
    }
    '/(vns)/comic_/$series/$chapter': {
      id: '/(vns)/comic_/$series/$chapter'
      path: '/comic/$series/$chapter'
      fullPath: '/comic/$series/$chapter'
      preLoaderRoute: typeof vnsComicSeriesChapterRouteImport
      parentRoute: typeof vnsRouteRoute
    }
    '/(vns)/api/auth/$': {
      id: '/(vns)/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof vnsApiAuthSplatRouteImport
      parentRoute: typeof vnsRouteRoute
    }
  }
}

interface vnsRouteRouteChildren {
  vnsProjectsRoute: typeof vnsProjectsRoute
  vnsStaffRoute: typeof vnsStaffRoute
  vnsStationComm1Route: typeof vnsStationComm1Route
  vnsIndexRoute: typeof vnsIndexRoute
  vnsApiSplatRoute: typeof vnsApiSplatRoute
  vnsComicSeriesRoute: typeof vnsComicSeriesRoute
  vnsComicIndexRoute: typeof vnsComicIndexRoute
  vnsApiAuthSplatRoute: typeof vnsApiAuthSplatRoute
  vnsComicSeriesChapterRoute: typeof vnsComicSeriesChapterRoute
}

const vnsRouteRouteChildren: vnsRouteRouteChildren = {
  vnsProjectsRoute: vnsProjectsRoute,
  vnsStaffRoute: vnsStaffRoute,
  vnsStationComm1Route: vnsStationComm1Route,
  vnsIndexRoute: vnsIndexRoute,
  vnsApiSplatRoute: vnsApiSplatRoute,
  vnsComicSeriesRoute: vnsComicSeriesRoute,
  vnsComicIndexRoute: vnsComicIndexRoute,
  vnsApiAuthSplatRoute: vnsApiAuthSplatRoute,
  vnsComicSeriesChapterRoute: vnsComicSeriesChapterRoute,
}

const vnsRouteRouteWithChildren = vnsRouteRoute._addFileChildren(
  vnsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  vnsRouteRoute: vnsRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
